runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: dist/birdwatcherclient/index.html
  upload: dist/birdwatcherclient/index.html
- url: /
  static_dir: dist/birdwatcherclient