#1 - build the app in a node container
FROM node:14.1.0-alpine as node
WORKDIR /usr/scr/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
#2 - serve the app in a nginx container
FROM nginx:1.17.10-alpine
COPY --from=node /usr/src/app/dist/birdwatcherclient /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf